version: 2
registries:
  npm-registry-npm-daznplatform-com:
    type: npm-registry
    url: https://npm.daznplatform.com
    username: "${{secrets.NPM_REGISTRY_NPM_DAZNPLATFORM_COM_USERNAME}}"
    password: "${{secrets.NPM_REGISTRY_NPM_DAZNPLATFORM_COM_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/London
  open-pull-requests-limit: 3
  target-branch: develop
  reviewers:
  - bkimminich
  labels:
  - dependencies
  ignore:
  - dependency-name: express-jwt
    versions:
    - 0.1.3
  - dependency-name: jsonwebtoken
    versions:
    - 0.4.0
  - dependency-name: sanitize-html
    versions:
    - 1.4.2
  - dependency-name: unzipper
    versions:
    - 0.9.15
  - dependency-name: sanitize-html
    versions:
    - 2.3.2
  - dependency-name: file-type
    versions:
    - 16.2.0
  registries:
  - npm-registry-npm-daznplatform-com
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    timezone: Europe/London
  open-pull-requests-limit: 3
  target-branch: develop
  reviewers:
  - bkimminich
  labels:
  - dependencies
  ignore:
  - dependency-name: "@angular-material-extensions/password-strength"
    versions:
    - 8.1.1
    - 8.2.0
  - dependency-name: "@nguniversal/express-engine"
    versions:
    - 10.1.0
    - 11.2.0
  - dependency-name: jasmine-spec-reporter
    versions:
    - 6.0.0
  registries:
  - npm-registry-npm-daznplatform-com
